;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Load user identity from secrets.el (generated by agenix)
(let ((secrets-file (expand-file-name "secrets.el" doom-user-dir)))
  (when (file-exists-p secrets-file)
    (load secrets-file)))

(setq doom-theme 'doom-one
      doom-font (font-spec :family "FiraCode Nerd Font" :size 12 :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13)
      display-line-numbers-type t)


(defun fixed-native-compile-async-skip-p
    (native-compile-async-skip-p file load selector)
  (let* ((naive-elc-file (file-name-with-extension file "elc"))
         (elc-file       (replace-regexp-in-string
                          "\\.el\\.elc$" ".elc" naive-elc-file)))
    (or (gethash elc-file comp--no-native-compile)
        (funcall native-compile-async-skip-p file load selector))))

(advice-add 'native-compile-async-skip-p
            :around 'fixed-native-compile-async-skip-p)

(when (and display-line-numbers-type (eq doom-theme 'doom-one))
  (custom-set-faces!
                                        ; default was #3f444a
    '(line-number :foreground "#646c75")))

;; which system am i on
(defconst current-system-type
  (if (string-prefix-p "TEN" (system-name))
      (intern "work")
    (intern "personal"))
  "Symbol for current system type. `work' or `personal'")
(defmacro with-system-type (&rest clauses)
  "Execute expressions based on `current-system-type`.
Each clause should be of the form `:work BODY...` or `:personal BODY...`,
in any order. BODY... can contain single or multiple expressions."
  (let ((work-body (plist-get clauses :work))
        (personal-body (plist-get clauses :personal)))
    (cond ((eq current-system-type 'work) `(progn ,@(if (listp work-body) work-body (list work-body))))
          ((eq current-system-type 'personal) `(progn ,@(if (listp personal-body) personal-body (list personal-body))))
          (t (error "invalid system type: %s" current-system-type)))))

(with-system-type
 :work ((let ((work-config-path (expand-file-name "work-config.el" doom-user-dir)))
          (when (file-exists-p work-config-path)
            (load work-config-path)))))
;; end system detection


;; Must be set before org loads!
(defvar org-directory-personal "~/Library/Mobile Documents/com~apple~CloudDocs/org")
(defvar org-directory-work "~/Documents/notes/")
(setq org-directory (with-system-type
                     :work org-directory-work
                     :personal org-directory-personal))

(when (file-directory-p (doom-path "lisp"))
  (add-load-path! (doom-path "lisp")))

(load! "lisp/local" doom-user-dir t)



(after! sh-mode
  (setq sh-basic-offset 2)
  (add-hook 'sh-mode-hook
            (function (lambda ()
                        (setq evil-shift-width sh-basic-offset)))))

(after! jq-mode
  (add-to-list 'auto-mode-alist '("\\.jq$" . jq-mode)))

(require 'tera-mode)


;; BEGIN: org-mode

(load! "lisp/org-funcs" doom-user-dir t)




;; (with-eval-after-load 'org
;;   (add-hook! 'org-mode-hook #'+org-pretty-mode)
;;   (add-hook! 'org-mode-hook #'my/org-hide-done-entries-in-buffer)
;;   (add-hook! 'org-mode-hook (lambda () (org-align-tags t) (message "aligned tags")))
;;   (add-hook! 'org-capture-mode-hook (lambda () (org-align-tags t))))

(defun personal-org-file (name)
  "Joins NAME with `org-directory-personal'."
  (concat (file-name-as-directory org-directory-personal) name))
(defun work-org-file (name)
  "Joins NAME with `org-directory-work'."
  (concat (file-name-as-directory org-directory-work) name))

(defvar +org-capture-personal-notes-file +org-capture-notes-file)
(defvar +org-capture-personal-todo-file +org-capture-todo-file)

(with-system-type
 :work ((setq +org-capture-notes-file (work-org-file "notes.org")
              +org-capture-todo-file (work-org-file "tasks.org")
              +org-capture-personal-notes-file (personal-org-file "notes.org")
              +org-capture-personal-todo-file (personal-org-file "tasks.org")))
 :personal ((setq +org-capture-notes-file (personal-org-file "personal.org")
                  +org-capture-todo-file (personal-org-file "personal.org"))))

(setq epg-pinentry-mode 'loopback
      epa-file-select-keys nil
      epa-file-encrypt-to nil
      epa-file-cache-passphrase-for-symmetric-encryption t)

(after! org
  (set-popup-rule! "^ \\*Org tags" :side 'bottom :size 0.80 :select t :ttl nil)
  (after! smartparens
    (sp-local-pair 'org-mode "=" "=" :unless '(sp-point-after-word-p) :post-handlers '(("[d1]" "SPC"))))

  (defun my/org-sp-insert-verbatim ()
    "Insert verbatim around the current selection."
    (interactive)
    (sp-wrap-with-pair "="))

  (defun my/org-get-top-level-heading ()
    "Get the content of the current top-level heading in org mode."
    (save-excursion
      (while (org-up-heading-safe)) ;; go to the top-level heading
      (org-get-heading 'notags 'nopriority 'nosection)))


  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (shell . t)))

  (setq org-journal-encrypt-journal t
        org-journal-dir "~/Documents/journal/"
        org-journal-file-type 'daily
        org-extend-today-until 3)

  (add-hook! 'org-mode-hook #'+org-pretty-mode)
  ;; (add-hook! 'org-mode-hook #'my/org-hide-done-entries-in-buffer)
  (add-hook! 'org-mode-hook (lambda () (org-align-tags t) (message "aligned tags")))
  (add-hook! 'org-capture-mode-hook (lambda () (org-align-tags t)))
  (map! :map org-mode-map
        :localleader
        "=" #'my/org-sp-insert-verbatim)
  (map! :map org-mode-map
        :after yasnippet
        ;; Retain org-mode's native TAB functionality but allow yas-expand when a snippet is available
        :nvi [tab] yas-maybe-expand
        ;; Optionally, bind other keys for snippet navigation
        :nvi "C-c n" #'yas-next-field
        :nvi "C-c p" #'yas-prev-field)

  (setq org-agenda-skip-scheduled-if-done t
        org-tags-column -100
        org-todo-keywords '((sequence "TODO(t)" "INPROGRESS(i)" "WAITING(w)" "|" "DONE(d)" "CANCELLED(c)")
                            (sequence "QUESTION(q)" "|" "YES(y!)" "NO(n!)" "COMMENT(c@)"))
        org-todo-keyword-faces
        '(("TODO" . org-todo)
          ("WAITING" . +org-todo-onhold)
          ("INPROGRESS" . +org-todo-active)
          ("DONE" . org-done)
          ("CANCELLED" . +org-todo-cancel)
          ("QUESTION" . +org-todo-active)
          ("YES" . org-cite)
          ("NO" . +org-todo-cancel)
          ("COMMENT" . org-drawer))
        ;; '(("TODO" . (:foreground (doom-color 'yellow) :weight bold :underline t))
        ;;   ("WAITING" . (:foreground (doom-color 'orange) :weight bold :underline t))
        ;;   ("INPROGRESS" . (:foreground (doom-color 'teal) :weight bold :underline t))
        ;;   ("DONE" . (:foreground (doom-color 'green) :weight bold :underline t))
        ;;   ("CANCELLED" . (:foreground (doom-color 'red) :weight bold :underline t)))
        ;; org-agenda-files (list "~/Documents/notes/tasks.org" "~/Documents/org/research.org")
        org-agenda-files (append (ignore-errors (directory-files org-directory-personal t "\\.org$" t)) (ignore-errors (directory-files org-directory-work t "\\.org$" t)))
        org-log-done 'time
        org-ellipsis " ▾ "
        org-capture-templates '(("t" "Work todo" entry
                                 (file+headline +org-capture-todo-file "Inbox")
                                 "* TODO %?\n%i\n%a" :prepend t)
                                ("C" "Collab topic" entry
                                 (file+headline +org-capture-todo-file "Collab")
                                 "* TODO %? :collab:\n%i\n%a" :prepend t)
                                ("T" "Personal todo" entry
                                 (file+headline +org-capture-personal-todo-file "Inbox")
                                 "* TODO %?\n%i\n%a" :prepend t)
                                ("n" "Work notes" entry
                                 (file+headline +org-capture-notes-file "Inbox")
                                 "* %u %?\n%i\n%a" :prepend t)
                                ("N" "Personal notes" entry
                                 (file+headline +org-capture-personal-todo-file "Notes")
                                 "* %u %?\n%i\n%a" :prepend t)
                                ;; ("j" "Journal" entry
                                ;;  (file+olp+datetree +org-capture-journal-file)
                                ;;  "* %U %?\n%i\n%a" :prepend t)
                                ("r" "Work Reference" entry
                                 (file+headline +org-capture-notes-file "Reference"))
                                ("R" "Personal Reference" entry
                                 (file+headline +org-capture-personal-todo-file "Reference"))
                                ("p" "Templates for projects")
                                ("pt" "Project-local todo" entry
                                 (file+headline +org-capture-project-todo-file "Inbox")
                                 "* TODO %?\n%i\n%a" :prepend t)
                                ("pn" "Project-local notes" entry
                                 (file+headline +org-capture-project-notes-file "Inbox")
                                 "* %U %?\n%i\n%a" :prepend t)
                                ("pc" "Project-local changelog" entry
                                 (file+headline +org-capture-project-changelog-file "Unreleased")
                                 "* %U %?\n%i\n%a" :prepend t)
                                ("o" "Centralized templates for projects")
                                ("ot" "Project todo" entry #'+org-capture-central-project-todo-file "* TODO %?\n %i\n %a" :heading "Tasks" :prepend nil)
                                ("on" "Project notes" entry #'+org-capture-central-project-notes-file "* %U %?\n %i\n %a" :heading "Notes" :prepend t)
                                ("oc" "Project changelog" entry #'+org-capture-central-project-changelog-file "* %U %?\n %i\n %a" :heading "Changelog" :prepend t))))

;; END: org-mode

(after! lsp-clangd
  (setq lsp-clients-clangd-args
        '("-j=3"
          "--background-index"
          "--clang-tidy"
          "--completion-style=detailed"
          "--header-insertion=never"
          "--header-insertion-decorators=0"))
  (set-lsp-priority! 'clangd 2))

(defun projectile-list-buffers ()
  (let ((project (projectile-acquire-root)))
    (projectile-project-buffers project)))

(use-package! lsp-mode
  :defer t
  :custom
  (lsp-completion-provider :none)
  :init
  (defun local/lsp-mode-setup-completion ()
    (setf (alist-get 'styles (alist-get 'lsp-capf completion-category-defaults))
          '(flex)))
  :hook
  (lsp-completion-mode . local/lsp-mode-setup-completion))

(defconst config/cargo-popup-size 0.4
  "Buffer size for Cargo popup windows")

(after! popup
  (set-popup-rule! "^\\*cargo-test\\*$" :side 'bottom :size config/cargo-popup-size :select t)
  (set-popup-rule! "^\\*cargo-clippy\\*$" :side 'bottom :size config/cargo-popup-size :select t))

(defun +lookup/definition-other-window (identifier &optional arg)
  (interactive (list (doom-thing-at-point-or-region)
                     current-prefix-arg))
  (cond ((null identifier) (user-error "Nothing under point"))
        ((+lookup--jump-to :definition identifier #'pop-to-buffer arg))
        ((user-error "Couldn't find the definition of %S" (substring-no-properties identifier)))))


(defun +lookup/references-other-window (identifier &optional arg)
  (interactive (list (doom-thing-at-point-or-region)
                     current-prefix-arg))
  (cond ((null identifier) (user-error "Nothing under point"))
        ((+lookup--jump-to :references identifier #'switch-to-buffer-other-window arg))
        ((user-error "Couldn't find references of %S" (substring-no-properties identifier)))))


(when (modulep! :tools lookup)
  (map! :nv "go" #'+lookup/definition-other-window
        :nv "gO" #'+lookup/references-other-window))

(defcustom centaur-tabs--local-buffer-blacklist
  '("*epc"
    "*helm"
    "*Helm"
    "*Compile-Log*"
    "*lsp"
    "*company"
    "*Flycheck"
    "*tramp"
    " *Mini"
    "*help"
    "*straight"
    " *temp"
    "*Help"
    "*mybuf")
  "List of buffer name prefixes to hide in tabs."
  :type '(list string))

(defun centaur-tabs-hide-tab (x)
  "Do not show buffer X in tabs."
  (let ((name (format "%s" x)))
    (or
     (window-dedicated-p (selected-window))
     (cl-some (lambda (s) (string-prefix-p s name)) centaur-tabs--local-buffer-blacklist)
     (and (string-prefix-p "magit" name)
          (not (file-name-extension name))))))

(defun centaur-tabs-blacklist-prefix (prefix)
  "Add a buffer name prefix to the blacklist for tabs."
  (interactive)
  (add-to-list 'centaur-tabs--local-buffer-blacklist prefix))

(after! centaur-tabs
  (setq centaur-tabs--buffer-show-groups t)
  (centaur-tabs-group-by-projectile-project))

(defmacro local/open-file-cmd (file)
  "Create a lambda command that opens FILE."
  `(lambda ()
     (interactive)
     (find-file ,file)))

;;;; Rust config

(after! rustic
  (defun local/rustic-cargo-current-test-no-capture ()
    "Run 'cargo test' for the test near point."
    (interactive)
    (rustic-compilation-process-live)
    (-if-let (test-to-run (setq rustic-test-arguments
                                (rustic-cargo--get-test-target)))
        (local/rustic-cargo-run-test test-to-run '("--" "--nocapture"))
      (message "Could not find test at point.")))

  (defun local/rustic-cargo-rerun-no-capture ()
    "Run 'cargo test -- --nocapture with `rustic-test-arguments'."
    (interactive)
    (local/rustic-cargo-run-test rustic-test-arguments '("--" "--nocapture")))
  (defun local/rustic-cargo-run-test (test args)
    "Run TEST which can be a single test or mod name."
    (let* ((c (append (list (rustic-cargo-bin) rustic-cargo-test-exec-command test) args))
           (buf rustic-test-buffer-name)
           (proc rustic-test-process-name)
           (mode 'rustic-cargo-test-mode))
      (rustic-compilation c (list :buffer buf :process proc :mode mode))))
  (defun local/toggle-rust-backtrace ()
    "toggle RUST_BACKTRACE env var"
    (interactive)
    (if (or (string-equal rustic-compile-backtrace "1") (string-equal rustic-compile-backtrace "full"))
        (setq rustic-compile-backtrace "0")
      (setq rustic-compile-backtrace "full"))
    (message (format "RUST_BACKTRACE set: %s" rustic-compile-backtrace)))
  (defun local/rustic-cargo-run-make (args)
    "Run TEST which can be a single test or mod name."
    (let* ((c (append (list (rustic-cargo-bin) "make" "--cwd" (lsp-workspace-root) "--makefile" (doom-path (lsp-workspace-root) "Makefile.toml")) args))
           (buf rustic-test-buffer-name)
           (proc rustic-test-process-name)
           (mode 'rustic-compilation-mode))
      (rustic-compilation c (list :buffer buf :process proc :mode mode))))
  (defun local/rustic-cargo-make-docs-open ()
    "Run TEST which can be a single test or mod name."
    (interactive)
    (local/rustic-cargo-run-make '("open-docs")))
  (defun local/rustic-cargo-make-docs ()
    "Run TEST which can be a single test or mod name."
    (interactive)
    (local/rustic-cargo-run-make '("docs")))
  (defun local/rustic-cargo-make-vscode-debug ()
    "Run TEST which can be a single test or mod name."
    (interactive)
    (local/rustic-cargo-run-make '("vscode-debug"))))

(defun local/rust-lsp-setup ()
  (setq lsp-ui-doc-show-with-mouse t)
  ;; (setq lsp-headerline-breadcrumb-enable t)
  ;; (setq lsp-ui-sideline-show-code-actions t)
  ;; (setq lsp-ui-sideline-show-hover t)
  ;;
  ;; inlay hints
  ;; (setq lsp-inlay-hint-enable nil)
  ;; (setq lsp-rust-analyzer-binding-mode-hints t)
  ;; (setq lsp-rust-analyzer-display-closure-return-type-hints t)
  ;; (setq lsp-rust-analyzer-display-reborrow-hints "never")
  ;; (setq lsp-rust-analyzer-closure-capture-hints t)
  ;; (setq lsp-semantic-tokens-enable t)
  (setq lsp-ui-peek-enable t))
(add-hook 'rust-mode-hook #'local/rust-lsp-setup)

(map! :after rustic
      :map rustic-mode-map
      :localleader
                                        ; b - build prefix
                                        ; t - test prefix
      :desc "Expand macro" "M" #'lsp-rust-analyzer-expand-macro
      :desc "Open Cargo.toml" "c" #'lsp-rust-analyzer-open-cargo-toml
      :desc "Open docs from docs.rs" "d" #'lsp-rust-analyzer-open-external-docs
      (:prefix ("m" . "Cargo make")
       :desc "Open docs" "D" #'local/rustic-cargo-make-docs-open
       :desc "Generate docs" "d" #'local/rustic-cargo-make-docs
       :desc "VS Code debug" "v" #'local/rustic-cargo-make-vscode-debug)
      (:prefix ("o" . "custom")
       :desc "current test (nocapture)" "t" #'local/rustic-cargo-current-test-no-capture
       :desc "re-run test (nocapture)" "T" #'local/rustic-cargo-rerun-no-capture
       :desc "toggle RUST_BACKTRACE" "b" #'local/toggle-rust-backtrace))




;;;; END Rust config

(map! :mode jsonnet-mode
      :map jsonnet-mode-map
      :localleader
      (:prefix ("e" . "eval")
       :desc "eval buffer" "b" #'jsonnet-eval-buffer))

(after! jsonnet-mode
  (add-to-list 'auto-mode-alist (cons "\\.jsonnet$" 'jsonnet-mode))
  (add-to-list 'auto-mode-alist (cons "\\.libsonnet$'" 'jsonnet-mode)))


(map! :mode mermaid-mode
      :map mermaid-mode-map
      :localleader
      :desc "Open browser" "b" #'mermaid-open-browser
      (:prefix ("c" . "compile")
               "f" #'mermaid-compile-file
               "b" #'mermaid-compile-buffer
               "r" #'mermaid-compile-region
               "c" #'mermaid-compile))

(after! graphviz-dot-mode
  (setq graphviz-dot-indent-width 4)
  ;; (add-hook 'graphviz-dot-mode-hook 'company-mode)
                                        ; (setq graphviz-dot-auto-preview-on-save t)
  (setq graphviz-dot-preview-extension "svg")
  (defun graphviz-toggle-live-preview ()
    "Toggle live preview for graphviz"
    (interactive)
    (if graphviz-dot-auto-preview-on-save
        (graphviz-turn-off-live-preview)
      (graphviz-turn-on-live-preview))))


(map! :mode graphviz-dot-mode
      :map graphviz-dot-mode-map
      :localleader
      :desc "Preview" "p" #'graphviz-dot-preview
      :desc "Compile" "c" #'compile
      :desc "View" "v" #'graphviz-dot-view
      :desc "Toggle live preview" "P" #'graphviz-toggle-live-preview)

(when (fboundp 'jsonc-mode)
  (add-to-list 'auto-mode-alist '("\\.jsonc" . jsonc-mode)))

(after! ligature-mode
  (setq +ligatures-extra-symbols
        '(;; org
          :name          "»"
          :src_block     "»"
          :src_block_end "«"
          :quote         "“"
          :quote_end     "”"
          ;; Functional
          :lambda        "λ"
          :def           "ƒ"
          :composition   "∘"
          :map           "↦"
          ;; Types
          :null          "∅"
          :true          "⊤"
          :false         "⊥"
          :int           "ℤ"
          :float         "ℝ"
          ;; :str           "𝕊"
          :bool          "𝔹"
          ;; :list          "𝕃"
          :list          "|]"
          ;; Flow
          :not           "￢"
          :in            "∈"
          :not-in        "∉"
          :and           "∧"
          :or            "∨"
          :for           "∀"
          :some          "∃"
          :return        "⟼"
          :yield         "⟻"
          ;; Other
          :union         "⋃"
          :intersect     "∩"
          :diff          "∖"
          :tuple         "⨂"
          :pipe          "∣"
          :dot           "•")))

(add-hook 'markdown-mode-hook
          (lambda ()
            (set-fill-column 110)))

(after! grip-mode
  (setq grip-theme 'dark))

(add-hook 'racket-xp-mode-hook
          (lambda ()
            (remove-hook 'pre-redisplay-functions
                         #'racket-xp-pre-redisplay
                         t)))

;; required setup:
;;  $ sudo port install emscripten tree-sitter-cli
;;  $ cd ~/.doom.d/
;;  $ git clone https://github.com/liamwh/tree-sitter-wit
;;  $ cd tree-sitter-wit
;;  # $ tree-sitter build --wasm --output ./build/parser.wasm .
;;  $ tree-sitter build --output ./build/parser.dylib .
;;  $ mkdir ~/.tree-sitter
;;  $ cp build/parser.dylib ~/.tree-sitter/tree-sitter-wit.dylib
;; (use-package! tree-sitter
;;   :config
;;   (add-to-list 'tree-sitter-load-path (expand-file-name "~/.tree-sitter/"))
;;   (tree-sitter-load 'wit "tree-sitter-wit"))

(use-package! wit-mode
  :mode ("\\.wit\\'" . wit-mode)
  :defer t)

;; (use-package! tree-sitter-langs
;;   :config
;;   (add-to-list 'tree-sitter-major-mode-language-alist '(wit-mode . wit)))

(use-package! gptel
  :defer t)

(use-package! key-chord
  :config
  (key-chord-mode 1)
  (key-chord-define-global "jf" 'evil-normal-state)
  :defer t)

(use-package! mermaid-mode
  :defer t)

                                        ;(use-package! ox-hugo)
                                        ;(use-package! ox-zola)

(after! (:and nix-mode lsp-mode)
  (setq nix-nixfmt-bin "alejandra"
        lsp-nix-nil-formatter ["alejandra"]))

(use-package! llvm-mode
  :defer t
  :config
  (setq llvm-mode-indent-offset 2)
  (setq llvm-mode-label-offset 2))

(use-package! silicon
  :config
  (setq silicon-default-theme "OneHalfDark"))
(map! :after silicon
      :map silicon-mode-map
      :leader
      :desc "Silicon code screenshot" :nv "cls" #'silicon-buffer-file-to-png)


(map! :leader
      :after silicon
      (:prefix ("l" . "custom local bindings")
               (:prefix ("c" . "config")
                :desc "Open doom config.el" "c" (local/open-file-cmd (doom-path doom-user-dir "config.el"))
                :desc "Open doom init.el" "i" (local/open-file-cmd (doom-path doom-user-dir "init.el"))
                :desc "Open doom packages.el" "p" (local/open-file-cmd (doom-path doom-user-dir "packages.el"))
                :desc "Open nix home-manager" "n" (local/open-file-cmd "~/.config/nix-darwin/modules/home-manager/default.nix"))
               (:prefix ("t" . "tabs")
                :desc "Toggle between file tabs and group tabs" "t" #'centaur-tabs-toggle-groups
                :desc "Blacklist a buffer name prefix, to be hidden in tabs" "b" #'centaur-tabs-blacklist-prefix
                :desc "Kill all buffers in the current tab group" "k" #'centaur-tabs-kill-all-buffers-in-current-group)
               (:prefix ("s" . "silicon")
                :desc "Silicon code screenshot" "s" #'silicon-buffer-file-to-png)))

(use-package! hoon-mode
  :defer t)
