{ config, lib, pkgs, host, ... }:

let
  homeDir = host.homeDirectory;
  secretsDir = ../../secrets;
in {
  # Declare agenix secrets
  age.secrets = {
    user-info = {
      file = "${secretsDir}/user-info.age";
      path = "${config.home.homeDirectory}/.local/share/agenix/user-info";
    };
    ssh-hosts = {
      file = "${secretsDir}/ssh-hosts.age";
      path = "${config.home.homeDirectory}/.local/share/agenix/ssh-hosts";
    };
  };

  # Activation scripts to generate config files from decrypted secrets
  home.activation = {
    # Generate git secrets config
    generateGitSecrets = lib.hm.dag.entryAfter [ "writeBoundary" "agenix" ] ''
      if [ -f "${config.age.secrets.user-info.path}" ]; then
        mkdir -p "${config.xdg.configHome}/git"
        source "${config.age.secrets.user-info.path}"
        cat > "${config.xdg.configHome}/git/secrets" <<EOF
[user]
    name = $USER_NAME
    email = $USER_EMAIL
EOF
        $DRY_RUN_CMD chmod 600 "${config.xdg.configHome}/git/secrets"
      fi
    '';

    # Generate jujutsu user config in conf.d/
    generateJujutsuSecrets = lib.hm.dag.entryAfter [ "writeBoundary" "agenix" ] ''
      if [ -f "${config.age.secrets.user-info.path}" ]; then
        mkdir -p "${config.xdg.configHome}/jj/conf.d"
        source "${config.age.secrets.user-info.path}"
        cat > "${config.xdg.configHome}/jj/conf.d/secrets.toml" <<EOF
[user]
name = "$USER_NAME"
email = "$USER_EMAIL"
EOF
        $DRY_RUN_CMD chmod 600 "${config.xdg.configHome}/jj/conf.d/secrets.toml"
      fi
    '';

    # Generate SSH secret hosts config
    generateSshSecretHosts = lib.hm.dag.entryAfter [ "writeBoundary" "agenix" ] ''
      if [ -f "${config.age.secrets.ssh-hosts.path}" ]; then
        mkdir -p "${homeDir}/.ssh/config.d"
        source "${config.age.secrets.ssh-hosts.path}"
        cat > "${homeDir}/.ssh/config.d/secret-hosts" <<EOF

EOF
        $DRY_RUN_CMD chmod 600 "${homeDir}/.ssh/config.d/secret-hosts"
      fi
    '';

    # Generate Doom Emacs secrets.el
    generateDoomSecrets = lib.hm.dag.entryAfter [ "writeBoundary" "agenix" ] ''
      if [ -f "${config.age.secrets.user-info.path}" ]; then
        source "${config.age.secrets.user-info.path}"
        cat > "${homeDir}/.doom.d/secrets.el" <<EOF
;;; secrets.el -*- lexical-binding: t; -*-
;;; This file is auto-generated by agenix. Do not edit manually.
(setq user-full-name "$USER_NAME"
      user-mail-address "$USER_EMAIL")
EOF
        $DRY_RUN_CMD chmod 600 "${homeDir}/.doom.d/secrets.el"
      fi
    '';
  };
}
